title: Meet Bhalodi
email: meet@yellojacket.dev
description: >- 
baseurl: ""
url: "https://mustard.yellowjacket.dev"
twitter_username: meetbhalodi11
github_username:  meetbhalodi11

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

collections:
  blogs:
    output: true
    permalink: /:path/
  
header_pages:
  - blogs.markdown
  - resolutions.markdown
  - about.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
