title: Meet Bhalodi
email: meet@yellojacket.dev
description: >- 
baseurl: ""
url: "https://mustard.yellowjacket.dev"
twitter_username: meetbhalodi11
github_username:  meetbhalodi11

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

collections:
  blogs:
    output: true
    permalink: /:path/
  
header_pages:
  - blogs.markdown
  - resolutions.markdown
  - ogs.markdown
  - about.markdown